# Introducción

**NumPy** es la *librería* de python para computación científica. **NumPy** agrega al lenguaje lo siguiente: Arreglos multidimensionales, operaciones elemento por elemento (técnica conocida como *broadcasting*), algebra lineal, manipulación de imágenes, la habilidad de utilizar código `C/C++` y `FORTRAN`, entre muchas otras.

La mayor parte de los componentes del sistema de computo científico de Python, están construidas encima de **NumPy**, un ejemplo que veremos en el curso es `SciPy`.

Para poder utilizar **NumPy**, es necesario importarlo a la sesión del `notebook`.

In [1]:
import numpy as np

## Arrays

El principal componente de **NumPy** es el `array`, el cual es una versión más poderosa, pero menos flexible que las listas de python.

In [2]:
lst =  [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
type(lst)

list

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
lst[2:3]

[3]

In [7]:
arr[2:3]

array([3])

<div class="alert alert-info">
**Ejercicio:** Repite los ejercicios de listas del *Lecture 2* con `array`.
</div>

In [8]:
lst[-1] = "Las listas pueden tener varios tipos de datos"
lst

[1, 2, 3, 4, 'Las listas pueden tener varios tipos de datos']

In [9]:
arr[-1] = "Los arreglos no..."

ValueError: invalid literal for long() with base 10: 'Los arreglos no...'

Una vez inicializado el `array` sólo puede contener un tipo de dato.

In [10]:
arr.dtype

dtype('int64')

In [11]:
arr[-1] = 1.23456
arr

array([1, 2, 3, 4, 1])

In [12]:
arr.dtype

dtype('int64')

Sacrificamos la versatilidad de las listas por velocidad. Creeemos un `array` de 1 millón de elementos y multiplicaremos cada uno de ellos por una constante (*broadcasting*).

In [13]:
arr = np.arange(1e6)  # Puedes intentar con 1e7 e 1e8 para ver como escala el cálculo en tiempo  

In [14]:
lst = arr.tolist()

In [15]:
type(lst)

list

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr.dtype

dtype('float64')

Las listas no soportan *broadcasting* por lo que crearemos una función que lo simule

In [18]:
def lst_multiplicacion( alist , scalar ): 
    for i , val in enumerate ( alist ): 
        alist [ i ] = val*scalar
    return alist

In [19]:
%timeit arr * 1.1

100 loops, best of 3: 1.42 ms per loop


In [20]:
%timeit lst_multiplicacion(lst, 1.1)

10 loops, best of 3: 102 ms per loop


## Creación de arrays

In [21]:
arr = np.array([1,2,3,4,5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr = np.arange(10,21)

In [24]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
arr = np.zeros(5)

In [26]:
arr

array([ 0.,  0.,  0.,  0.,  0.])

In [27]:
arr = np.linspace(0,1,100)

In [28]:
arr

array([ 0.        ,  0.01010101,  0.02020202,  0.03030303,  0.04040404,
        0.05050505,  0.06060606,  0.07070707,  0.08080808,  0.09090909,
        0.1010101 ,  0.11111111,  0.12121212,  0.13131313,  0.14141414,
        0.15151515,  0.16161616,  0.17171717,  0.18181818,  0.19191919,
        0.2020202 ,  0.21212121,  0.22222222,  0.23232323,  0.24242424,
        0.25252525,  0.26262626,  0.27272727,  0.28282828,  0.29292929,
        0.3030303 ,  0.31313131,  0.32323232,  0.33333333,  0.34343434,
        0.35353535,  0.36363636,  0.37373737,  0.38383838,  0.39393939,
        0.4040404 ,  0.41414141,  0.42424242,  0.43434343,  0.44444444,
        0.45454545,  0.46464646,  0.47474747,  0.48484848,  0.49494949,
        0.50505051,  0.51515152,  0.52525253,  0.53535354,  0.54545455,
        0.55555556,  0.56565657,  0.57575758,  0.58585859,  0.5959596 ,
        0.60606061,  0.61616162,  0.62626263,  0.63636364,  0.64646465,
        0.65656566,  0.66666667,  0.67676768,  0.68686869,  0.69

In [29]:
arr = np.logspace(0,1,100, base=10)

In [30]:
arr

array([  1.        ,   1.02353102,   1.04761575,   1.07226722,
         1.09749877,   1.12332403,   1.149757  ,   1.17681195,
         1.20450354,   1.23284674,   1.26185688,   1.29154967,
         1.32194115,   1.35304777,   1.38488637,   1.41747416,
         1.45082878,   1.48496826,   1.51991108,   1.55567614,
         1.59228279,   1.62975083,   1.66810054,   1.70735265,
         1.7475284 ,   1.78864953,   1.83073828,   1.87381742,
         1.91791026,   1.96304065,   2.009233  ,   2.05651231,
         2.10490414,   2.15443469,   2.20513074,   2.25701972,
         2.3101297 ,   2.36448941,   2.42012826,   2.47707636,
         2.53536449,   2.59502421,   2.65608778,   2.71858824,
         2.7825594 ,   2.84803587,   2.91505306,   2.98364724,
         3.05385551,   3.12571585,   3.19926714,   3.27454916,
         3.35160265,   3.43046929,   3.51119173,   3.59381366,
         3.67837977,   3.76493581,   3.85352859,   3.94420606,
         4.03701726,   4.1320124 ,   4.22924287,   4.32

In [31]:
arr2d = np.zeros((5,5))

In [32]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [33]:
cubo = np.zeros((5,5,5)).astype(int)+1

In [34]:
cubo

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [35]:
cubo = np.ones((5,5,5)).astype(np.float16)

In [36]:
cubo

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]], dtype=float16)

In [37]:
cubo.dtype

dtype('float16')

In [38]:
np.empty((2,3,4))

array([[[  0.00000000e+000,   2.31584192e+077,   5.92878775e-323,
           0.00000000e+000],
        [  2.12199579e-314,   3.51022257e+151,   1.30424409e-142,
           3.97084747e+246],
        [  2.77621464e+184,   8.76739488e+252,   1.14011198e+243,
           5.54175224e+257]],

       [[  5.48213907e-143,   2.91945954e-014,   6.97283618e+228,
           1.47251095e-052],
        [  6.32306726e+233,   7.68655460e-072,   6.02182527e+151,
           9.30537465e+199],
        [  2.20835466e-094,   5.50028887e+247,   2.15799222e+243,
           1.66880754e-308]]])

<div class="alert alert-danger">
**PELIGRO**

¡`np.empty` no devuelve un arreglo de ceros!
</div>

In [39]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [40]:
np.random.rand(3)

array([ 0.98158699,  0.238681  ,  0.72109297])

## Reshaping

In [41]:
arr = np.arange(1000)

In [42]:
arr3d = arr.reshape((10,10,10))

In [43]:
arr3d.ndim

3

In [44]:
arr3d.shape

(10, 10, 10)

In [45]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [46]:
arr = np.arange(200)

In [47]:
arr2d = arr.reshape((10,20))

In [48]:
arr2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

## Aplanar

In [49]:
arr = np.zeros((4,4,4,4))
arr

array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.

In [50]:
arr.shape

(4, 4, 4, 4)

In [51]:
arr_plano = arr.ravel()

In [52]:
arr_plano

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [53]:
arr_plano.shape

(256,)

## *Broadcasting*

In [54]:
data = np.array([1,2,3,4,5])

In [55]:
data

array([1, 2, 3, 4, 5])

In [56]:
data + 1

array([2, 3, 4, 5, 6])

In [57]:
data * 2

array([ 2,  4,  6,  8, 10])

In [58]:
data ** 2

array([ 1,  4,  9, 16, 25])

## Transponer

In [59]:
arr = np.arange(15).reshape((3,5))

In [60]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

¿Qué pasa en varias dimensiones?

In [62]:
arr  = np.arange(16).reshape((2,2,4))

In [63]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [64]:
arr.transpose((1,2,0)).shape

(2, 4, 2)

`transpose` recibe una `tupla` de los índices de los ejes y los permuta. `(O_o)`

<div class="alert alert-info">
**Ejercicio** Diseña un ejemplo multidimensional, donde sea obvia la permutación
</div>

## Slicing e Indexado

En el ejercicio vimos que el indexado en `arrays` de 1D es igual que el indexado y *slicing* de las listas de python. ¿Pero que sucede en $n-$dimensiones?

### Cuidado al hacer *slicing*

In [65]:
arr = np.arange(10)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

El _slincing_ genera (devuelve) una **vista**, si modificas el =array= original, la **vista** se ve modificada también.

In [67]:
arr_slice =  arr[5:8]

In [68]:
arr_slice

array([5, 6, 7])

In [69]:
arr_slice[1]= 12345678

In [70]:
arr_slice

array([       5, 12345678,        7])

In [71]:
arr

array([       0,        1,        2,        3,        4,        5,
       12345678,        7,        8,        9])

In [72]:
arr_slice[:] = 345

In [73]:
arr_slice

array([345, 345, 345])

In [74]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [75]:
arr2 = np.copy(arr)

In [76]:
arr2

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [77]:
arr2[5:8] = [5,6,7]

In [78]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr

array([  0,   1,   2,   3,   4, 345, 345, 345,   8,   9])

In [80]:
np.may_share_memory(arr, arr_slice)

True

In [81]:
np.may_share_memory(arr, arr2)

False

### Multidimensional

In [82]:
arr = np.arange(9)

In [83]:
arr.shape = (3,3)

In [84]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
arr.ndim

2

In [86]:
arr[2]

array([6, 7, 8])

In [87]:
arr[-1]

array([6, 7, 8])

In [88]:
arr[1][1]

4

In [89]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [90]:
arr[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [91]:
arr[:1,:2]

array([[0, 1]])

In [92]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
arr[1:,:2]

array([[3, 4],
       [6, 7]])

In [94]:
arr[1,]

array([3, 4, 5])

In [95]:
arr[1,:2]

array([3, 4])

In [96]:
arr[1,2:]

array([5])

In [97]:
arr[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [98]:
arr[:,:1]

array([[0],
       [3],
       [6]])

<div class="alert alert-info">
**Ejercicio**:

Explique como funciona el *slicing* $n$-dimensional.
</div>

<div class="alert alert-info">
**Ejercicio**:
<ul>
    
    <li> Cree un arreglo $3\times4\times5$, con  $1$s de tipo `int`. </li>
    <li> Usando *slicing*, obtenga la columna de enmedio. </li>
    <li> Usando *indexing*, obtenga el valor del elemento $[3,4,1]$. </li>
    <li> Usando *slicing*, asigne el valor `1.34` a la $[2,3,]$ ¿Qué paso debe de hacer antes? </li>
    </ul>
</div>

In [99]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
index = arr > 2

In [101]:
index

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [102]:
arr[index]

array([3, 4, 5, 6, 7, 8])

In [103]:
arr2 = arr[index]

In [104]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
arr2

array([3, 4, 5, 6, 7, 8])

<div class="alert alert-info">
**Ejercicio:**
(a) Cree un arreglo de 2D $5\times5$ lleno de unos. (b) Utilice *slicing* para seleccionar 1 cuadrado alrededor del centro  y llénelo con $2$s.  (c) Utilice *slicing* para seleccionar  el centro y asígnele $4$. (d) Copie el arreglo. (e) Utilice *slicing* lógico para seleccionar el cuadro interno y asígnele cero. (f) En el cuadro copiado, al centro y al cuadro exterior asígnele $0$.
</div>

## Fancy Indexing

In [106]:
arr = np.ones((5,4))

In [107]:
for i in range(5):
    arr[i] = i

In [108]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.]])

In [109]:
arr[[4,3,1,2]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.]])

In [110]:
arr[[-3,-2,-1]]

array([[ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.]])

¿Puedes explicar que hace el _fancy indexing_?

## Funciones Universales

Las *funciones universales*  realizan operaciones elemento por elemento en los arreglos. 

In [111]:
arr = np.arange(10)

In [112]:
arr = -1*arr

In [113]:
arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [114]:
arr = np.abs(arr)

In [115]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [117]:
np.sign(arr)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [118]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [119]:
np.logical_not(arr)

array([ True, False, False, False, False, False, False, False, False, False], dtype=bool)

In [120]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
arr = np.random.randn(10)

In [122]:
arr

array([ 1.08039863,  0.64832405,  0.35621463,  1.33382099,  0.70965582,
       -0.05011372,  0.37599859, -0.58141217,  0.65323774,  0.19844978])

In [123]:
np.ceil(arr)

array([ 2.,  1.,  1.,  2.,  1., -0.,  1., -0.,  1.,  1.])

In [124]:
np.floor(arr)

array([ 1.,  0.,  0.,  1.,  0., -1.,  0., -1.,  0.,  0.])

In [125]:
np.rint(arr)

array([ 1.,  1.,  0.,  1.,  1., -0.,  0., -1.,  1.,  0.])

In [126]:
arr2 = np.ones(10)

In [127]:
np.add(arr, arr2)

array([ 2.08039863,  1.64832405,  1.35621463,  2.33382099,  1.70965582,
        0.94988628,  1.37599859,  0.41858783,  1.65323774,  1.19844978])

In [128]:
np.multiply(arr, arr2)

array([ 1.08039863,  0.64832405,  0.35621463,  1.33382099,  0.70965582,
       -0.05011372,  0.37599859, -0.58141217,  0.65323774,  0.19844978])

In [129]:
np.maximum(arr, arr2)

array([ 1.08039863,  1.        ,  1.        ,  1.33382099,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])

In [130]:
np.logical_and(arr, arr2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

## Agregaciones

Funciones que calculan operaciones a lo largo de un eje.

In [131]:
arr

array([ 1.08039863,  0.64832405,  0.35621463,  1.33382099,  0.70965582,
       -0.05011372,  0.37599859, -0.58141217,  0.65323774,  0.19844978])

In [132]:
arr.sum()

4.7245743456959346

In [133]:
arr.mean()

0.47245743456959344

In [134]:
arr = np.random.randn(5,4)

In [135]:
arr

array([[-0.70058259,  0.22832244,  1.62992861, -0.48164455],
       [-0.82213989, -1.06830707,  0.57200147, -0.20370586],
       [-0.52904089,  0.28319216,  1.65083101,  0.68199789],
       [-1.38379554,  0.93348779,  1.67259935,  0.67275963],
       [ 0.11864099,  0.21112334, -0.19940554, -0.02098283]])

In [136]:
arr.sum()

3.2452799253823623

In [137]:
arr.mean()

0.16226399626911811

In [138]:
arr.sum(0)

array([-3.31691791,  0.58781865,  5.3259549 ,  0.64842429])

In [139]:
arr = np.arange(10)

In [140]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [141]:
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [142]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [143]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [144]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [145]:
(arr > 5).sum()

4

## Operaciones de conjuntos

In [146]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
arr2

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [148]:
np.unique(arr2)

array([ 1.])

In [149]:
np.intersect1d(arr, arr2)

array([ 1.])

<div class="alert alert-info">
**Ejercicio** Usando la definición de [**cuadrados mágicos**](http://en.wikipedia.org/wiki/Magic_square) crea una función que reciba un arreglo e indique si es o no un cuadrado mágico.
</div>

## Casting

In [150]:
a = np.array([1,2,3])
a

array([1, 2, 3])

El tipo de mayor jerarquía define el _cast_

In [151]:
a + 1.5

array([ 2.5,  3.5,  4.5])

La asignación **no** cambia el tipo del arreglo.

In [152]:
a.dtype

dtype('int64')

In [153]:
(a + 1.5).dtype

dtype('float64')

## Tipos 

In [154]:
 np.iinfo(np.int32).max, 2**31 - 1   # Prueba con 8, 16, 32 y 64 bits

(2147483647, 2147483647)

<div class="alert alert-info">
**Ejercicio** ¿Qué pasa con `int`?
</div>

In [155]:
np.finfo(np.float64).max 

1.7976931348623157e+308

In [156]:
np.finfo(np.float64).eps

2.2204460492503131e-16

In [157]:
np.float32(1e-8) + np.float32(1) == 1

True

In [158]:
np.float64(1e-8) + np.float64(1) == 1

False

## Estructura de datos

In [159]:
muestra = np.zeros((6,), dtype=[('codigo', 'S4'),('posicion', float), ('valor', float)])

In [160]:
muestra

array([('', 0.0, 0.0), ('', 0.0, 0.0), ('', 0.0, 0.0), ('', 0.0, 0.0),
       ('', 0.0, 0.0), ('', 0.0, 0.0)], 
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [161]:
muestra.ndim

1

In [162]:
muestra.shape

(6,)

In [163]:
muestra.dtype.names

('codigo', 'posicion', 'valor')

In [164]:
muestra[:] = [('ALFA',   1, 0.37), ('BETA', 1, 0.11), ('TAU', 1,   0.13),('ALFA', 1.5, 0.37), ('ALFA', 3, 0.11), ('TAU', 1.2, 0.13)]

In [165]:
muestra

array([('ALFA', 1.0, 0.37), ('BETA', 1.0, 0.11), ('TAU', 1.0, 0.13),
       ('ALFA', 1.5, 0.37), ('ALFA', 3.0, 0.11), ('TAU', 1.2, 0.13)], 
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

In [166]:
muestra.shape

(6,)

In [167]:
muestra['codigo']

array(['ALFA', 'BETA', 'TAU', 'ALFA', 'ALFA', 'TAU'], 
      dtype='|S4')

In [168]:
muestra[0]['valor']

0.37

In [169]:
muestra[['codigo', 'valor']]

array([('ALFA', 0.37), ('BETA', 0.11), ('TAU', 0.13), ('ALFA', 0.37),
       ('ALFA', 0.11), ('TAU', 0.13)], 
      dtype=[('codigo', 'S4'), ('valor', '<f8')])

In [170]:
muestra[muestra['codigo'] == 'ALFA']

array([('ALFA', 1.0, 0.37), ('ALFA', 1.5, 0.37), ('ALFA', 3.0, 0.11)], 
      dtype=[('codigo', 'S4'), ('posicion', '<f8'), ('valor', '<f8')])

## Broadcasting (Segunda vuelta)

<div class="alert alert-warning">
**NOTA** Las imágenes y ejemplos están basados en la presentación  **The NumPy Array: A Structure for
Efficient Numerical Computation** de _Stéfan van der Walt_ de 2010.
</div>

### 1D

<img src="images/broadcasting_1d.png"/>

In [171]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [172]:
x + 3

array([3, 4, 5, 6])

### 2D

<img src="images/broadcasting_2d.png"/>

In [ ]:
a = np.arange(12).reshape((3,4))
print a.shape
a

In [ ]:
b = np.array([1,2,3])
print b.shape
b

In [ ]:
a+b

<div class="alert alert-danger">
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

In [ ]:
b = b[:, np.newaxis]
print b.shape
b

In [ ]:
a + b

### 3D

<img src="images/broadcasting_3d.png"/>

In [ ]:
x = np.zeros((3,5))
x

In [ ]:
y = np.zeros(8)

In [ ]:
x + y

<div class="alert alert-danger">
**Observa muy bien lo que acaba de pasar, el error es a propósito...**
</div>

<div class="alert alert-info">
En la siguiente instrucción vamos a introducir el operador `Ellipsis` ($\ldots$)
</div>

In [ ]:
x[...,None]

<div class="alert alert-success">
El operador Ellipsis ($\ldots$)es usado como un _indicador_ para el resto de las dimensiones del arreglo que no están siendo especificadas. Una manera de verlo es como el `full slice` `[:]` para todas las dimensiones que están sin indicar, por ejemplo para el arreglo de tres dimensiones `a`, `a[...,0]`es lo mismo que `a[:,:,0]`. Para un arreglo de cuatro dimensiones, `b[...,0]`es lo mismo que `b[:,:,:,0]` y en el caso de `b[0,...,0]` es `b[0,:,:,0]`.
</div>

<div class="alert alert-info">
**Ejercicio** ¿Cuál es el equivalente para el arreglo $x$?
</div>

In [ ]:
z = (x[...,None] + y )
print z.shape
z

## Numpy y los otros lenguajes

### Diferencias entre GNU/Octave (Matlab) y NumPy

Como veremos en la lección [`5-algebra-lineal`](5-algebra_lineal.ipynb) tiene, además de la clase `ndarray`, la clase `matrix`. Esta clase tiene una sintáxis más parecida a la de `octave`. Esto permitirá transformar código de un lenguaje a otro (_casi_) sin problemas.

Para ver la equivalencia puedes consultar [aquí](http://wiki.scipy.org/NumPy_for_Matlab_Users).

### Comparación entre NumPy/Python, GNU/Octave y R

En esta [liga](http://hyperpolyglot.org/numerical-analysis) se puede consultar una tabla para los tres lenguajes.

[Otra liga](http://folk.uio.no/inf3330/scripting/doc/python/matlab-python-xref.pdf) donde se comparan los tres lenguajes.

### Bibliografía de soporte

- *NumPy Beginner's Guide* _Ivan Idris_,  PACKT Publishing, 2012
- *NumPy Cookbook* _Ivan Idris_, PACKT Publishing, 2012
- *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython*, _Wes McKinney_, O'REILLY, 2012